### ISSUE TITLE
Remove deprecated xWebConfigKeyValue resource in future release

### ISSUE THREAD

**Issue by dave-sampson13** [dsccommunity/WebAdministrationDsc#369]
#330 replaces the xWebConfigKeyValue resource with new resources that provide more comprehensive functionality. Suggest the xWebConfigKeyValue resource is removed in a future release.

**Comment by davetapley** [comment]
I saw that `xWebConfigKeyValue` is deprecated so I tried using `xWebConfigProperty` to set  some `AppSettings`, but I couldn't get it to work.

Before removing can you give an example (and maybe add to docs) of how e.g. ⬇️ would be converted to a `xWebConfigProperty`?

https://github.com/dsccommunity/xWebAdministration/blob/92b76d6558248b8c484ad772ab3123e6b7a49ffe/source/Examples/Resources/xWebConfigKeyValue/Sample_xWebConfigKeyValue_AddAppSetting.ps1#L25-L32
