### ISSUE TITLE
xWebsite: finds certificates with no private key to bind to SSL.  Doesn't choose a cert with most available time.

### ISSUE THREAD

**Issue by ThomasHughesIV** [dsccommunity/WebAdministrationDsc#578]
#### Details of the scenario you tried and the problem that is occurring
  Using xWebSite to deploy SSL certificates using a subject name.  When multiple certificates exist with the same subject name, xwebsite chooses one at random, not one with the most useable time.  When multiple certificates exist with the same subject name, and one doesn't have a private key, the code may pick that cert and attempt to bind it to SSL, causing an error.

#### Verbose logs showing the problem
NA to share for security reasons

#### Suggested solution to the issue
Replace line 1476 with:
$Certificate = Find-Certificate @FindCertificateSplat | Where-Object {$_.HasPrivateKey -eq $true} | Sort-Object -Property NotAfter -Descending | Select-Object -First 1

#### The DSC configuration that is used to reproduce the issue (as detailed as possible)
```powershell
        xWebSite BindCert {
            Ensure = 'Present'
            Name = 'Default Web Site'
            BindingInfo     = @(
                MSFT_xWebBindingInformation
                {
                    Protocol              = 'HTTPS'
                    Port                  = 443
                    CertificateSubject    = 'CN=DuplicateSubject'
                    CertificateStoreName  = 'MY'
                }
            )
        }
```

#### Version of the DSC module that was used
3.1.1.1

**Comment by Joe-Rennert** [comment]
We're experiencing this issue and hoping for a fix.  I see PR #579 was created, but has not seen any movement in a while.  Has it been abandoned?  Can I help in anyway?

**Comment by johlju** [comment]
Yes it has been abandoned. I would need a unit test that validate the change. @Joe-Rennert if you have time then I suggest sending in a new PR with the change plus a unit test.

**Comment by ThomasHughesIV** [comment]
Sorry, i do not know anything about 7nit tests. Was hoping i had some time
to learn.

**Comment by johlju** [comment]
No worries @ThomasHughesIV. Hopefully another contributor continue the work. 🙂
